version: 1.0.{build}
image: Visual Studio 2017
environment:
 matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
before_build:
 - appveyor-retry dotnet restore -v Minimal
build:
  verbosity: minimal
on_success:
- curl -s -o copilot https://copilot-test.blackducksoftware.com/ci/appveyor/scripts/upload
- bash copilot
